library("ggplot2")
library(cowplot)
library(egg)
library(ggpubr)

df <- read.delim("CRISPR_CAS_proximity_training_data.txt", header=FALSE) # # Load CRISPR_CAS_proximity_training_data.txt file provided in the Database files.
colnames(df) <- c("Array","Subtype","Distance","Pos","Match")

pIA_correct_base <- ggplot(subset(df,Subtype=="I-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIA_correct_dense <- ggplot(subset(df,Subtype=="I-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIA_aligned_plots <- align_plots(pIA_correct_base, pIA_correct_dense, align="hv", axis="tblr")
pIA_correct <- ggdraw(pIA_aligned_plots[[1]]) + draw_plot(pIA_aligned_plots[[2]])

pIA_wrong_base <- ggplot(subset(df,Subtype=="I-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIA_wrong_dense <- ggplot(subset(df,Subtype=="I-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIA_aligned_plots <- align_plots(pIA_wrong_base, pIA_wrong_dense, align="hv", axis="tblr")
pIA_wrong <- ggdraw(pIA_aligned_plots[[1]]) + draw_plot(pIA_aligned_plots[[2]])

pIB_correct_base <- ggplot(subset(df,Subtype=="I-B"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIB_correct_dense <- ggplot(subset(df,Subtype=="I-B"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIB_aligned_plots <- align_plots(pIB_correct_base, pIB_correct_dense, align="hv", axis="tblr")
pIB_correct <- ggdraw(pIB_aligned_plots[[1]]) + draw_plot(pIB_aligned_plots[[2]])

pIB_wrong_base <- ggplot(subset(df,Subtype=="I-B"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIB_wrong_dense <- ggplot(subset(df,Subtype=="I-B"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIB_aligned_plots <- align_plots(pIB_wrong_base, pIB_wrong_dense, align="hv", axis="tblr")
pIB_wrong <- ggdraw(pIB_aligned_plots[[1]]) + draw_plot(pIB_aligned_plots[[2]])

pIC_correct_base <- ggplot(subset(df,Subtype=="I-C"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIC_correct_dense <- ggplot(subset(df,Subtype=="I-C"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIC_aligned_plots <- align_plots(pIC_correct_base, pIC_correct_dense, align="hv", axis="tblr")
pIC_correct <- ggdraw(pIC_aligned_plots[[1]]) + draw_plot(pIC_aligned_plots[[2]])

pIC_wrong_base <- ggplot(subset(df,Subtype=="I-C"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIC_wrong_dense <- ggplot(subset(df,Subtype=="I-C"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pIC_aligned_plots <- align_plots(pIC_wrong_base, pIC_wrong_dense, align="hv", axis="tblr")
pIC_wrong <- ggdraw(pIC_aligned_plots[[1]]) + draw_plot(pIC_aligned_plots[[2]])

pID_correct_base <- ggplot(subset(df,Subtype=="I-D"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pID_correct_dense <- ggplot(subset(df,Subtype=="I-D"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pID_aligned_plots <- align_plots(pID_correct_base, pID_correct_dense, align="hv", axis="tblr")
pID_correct <- ggdraw(pID_aligned_plots[[1]]) + draw_plot(pID_aligned_plots[[2]])

pID_wrong_base <- ggplot(subset(df,Subtype=="I-D"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pID_wrong_dense <- ggplot(subset(df,Subtype=="I-D"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
pID_aligned_plots <- align_plots(pID_wrong_base, pID_wrong_dense, align="hv", axis="tblr")
pID_wrong <- ggdraw(pID_aligned_plots[[1]]) + draw_plot(pID_aligned_plots[[2]])

pIE_correct_base <- ggplot(subset(df,Subtype=="I-E"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIE_correct_dense <- ggplot(subset(df,Subtype=="I-E"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIE_correct_base, pIE_correct_dense, align="hv", axis="tblr")
pIE_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIE_wrong_base <- ggplot(subset(df,Subtype=="I-E"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIE_wrong_dense <- ggplot(subset(df,Subtype=="I-E"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIE_wrong_base, pIE_wrong_dense, align="hv", axis="tblr")
pIE_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIF_correct_base <- ggplot(subset(df,Subtype=="I-F"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIF_correct_dense <- ggplot(subset(df,Subtype=="I-F"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIF_correct_base, pIF_correct_dense, align="hv", axis="tblr")
pIF_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIF_wrong_base <- ggplot(subset(df,Subtype=="I-F"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIF_wrong_dense <- ggplot(subset(df,Subtype=="I-F"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIF_wrong_base, pIF_wrong_dense, align="hv", axis="tblr")
pIF_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIA_correct_base <- ggplot(subset(df,Subtype=="II-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIA_correct_dense <- ggplot(subset(df,Subtype=="II-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIA_correct_base, pIIA_correct_dense, align="hv", axis="tblr")
pIIA_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIA_wrong_base <- ggplot(subset(df,Subtype=="II-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIA_wrong_dense <- ggplot(subset(df,Subtype=="II-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIA_wrong_base, pIIA_wrong_dense, align="hv", axis="tblr")
pIIA_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIC_correct_base <- ggplot(subset(df,Subtype=="II-C"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIC_correct_dense <- ggplot(subset(df,Subtype=="II-C"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIC_correct_base, pIIC_correct_dense, align="hv", axis="tblr")
pIIC_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIC_wrong_base <- ggplot(subset(df,Subtype=="II-C"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIC_wrong_dense <- ggplot(subset(df,Subtype=="II-C"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIC_wrong_base, pIIC_wrong_dense, align="hv", axis="tblr")
pIIC_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIIA_correct_base <- ggplot(subset(df,Subtype=="III-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIIA_correct_dense <- ggplot(subset(df,Subtype=="III-A"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIIA_correct_base, pIIIA_correct_dense, align="hv", axis="tblr")
pIIIA_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIIA_wrong_base <- ggplot(subset(df,Subtype=="III-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIIA_wrong_dense <- ggplot(subset(df,Subtype=="III-A"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIIA_wrong_base, pIIIA_wrong_dense, align="hv", axis="tblr")
pIIIA_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIIB_correct_base <- ggplot(subset(df,Subtype=="III-B"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIIB_correct_dense <- ggplot(subset(df,Subtype=="III-B"&Match=="correct"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIIB_correct_base, pIIIB_correct_dense, align="hv", axis="tblr")
pIIIB_correct <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIIIB_wrong_base <- ggplot(subset(df,Subtype=="III-B"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_histogram(binwidth = 500,alpha=0) +xlim(0,100000)  + scale_y_continuous(name = "Count")+theme(legend.position = "none",text=element_text(size = 14,face="bold"))
pIIIB_wrong_dense <- ggplot(subset(df,Subtype=="III-B"&Match=="wrong"), aes(x = Distance, fill = Pos)) + geom_density(adjust=0.05,alpha=0.5)+scale_y_continuous(position = "left")+xlim(0,100000) +theme(panel.background = element_rect(fill='transparent'),plot.background = element_rect(fill='transparent', color=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),legend.background = element_rect(fill='transparent'),legend.box.background = element_rect(fill='transparent'),text=element_text(size = 14,face="bold"),legend.position = "top") + rremove("x.axis")+rremove("xlab") +rremove("x.text") +rremove("x.ticks") + rremove("y.axis")+rremove("ylab") +rremove("y.text") +rremove("y.ticks")
aligned_plots <- align_plots(pIIIB_wrong_base, pIIIB_wrong_dense, align="hv", axis="tblr")
pIIIB_wrong <- ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])

pIA <- ggarrange(pIA_correct, pIA_wrong, nrow=2,labels=c("IA - Correct Match","IA - Wrong Match"),common.legend = TRUE, legend="top")
pIB <- ggarrange(pIB_correct, pIB_wrong, nrow=2,labels=c("IB - Correct Match","IB - Wrong Match"),common.legend = TRUE, legend="top")
pIC <- ggarrange(pIC_correct, pIC_wrong, nrow=2,labels=c("IC - Correct Match","IC - Wrong Match"),common.legend = TRUE, legend="top")
pID <- ggarrange(pID_correct, pID_wrong, nrow=2,labels=c("ID - Correct Match","ID - Wrong Match"),common.legend = TRUE, legend="top")
pIE <- ggarrange(pIE_correct, pIE_wrong, nrow=2,labels=c("IE - Correct Match","IE - Wrong Match"),common.legend = TRUE, legend="top")
pIF <- ggarrange(pIF_correct, pIF_wrong, nrow=2,labels=c("IF - Correct Match","IF - Wrong Match"),common.legend = TRUE, legend="top")
pIIA <- ggarrange(pIIA_correct, pIIA_wrong, nrow=2,labels=c("IIA - Correct Match","IIA - Wrong Match"),common.legend = TRUE, legend="top")
pIIC <- ggarrange(pIIC_correct, pIIC_wrong, nrow=2,labels=c("IIC - Correct Match","IIC - Wrong Match"),common.legend = TRUE, legend="top")
pIIIA <- ggarrange(pIIIA_correct, pIIIA_wrong, nrow=2,labels=c("IIIA - Correct Match","IIIA - Wrong Match"),common.legend = TRUE, legend="top")
pIIIB <- ggarrange(pIIIB_correct, pIIIB_wrong, nrow=2,labels=c("IIIB - Correct Match","IIIB - Wrong Match"),common.legend = TRUE, legend="top")

